defaults:
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    direction: "maximize"
    n_trials: 20
    n_jobs: 1

nlp:
  experiment: "NLPClassifier"
  random_state: 0
  hidden_layer_sizes: 16
  activation: "relu"
  solver: "adam"
  batch_size: "auto"
  max_iter: 100
  early_stopping: True
